# Generated by Django 4.0.5 on 2023-01-16 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=500)),
                ('burnout_cal', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=500)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fintake', models.FloatField()),
                ('ahours', models.CharField(max_length=25)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.activities')),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
